@startuml
+class UsingTheAnnotation{
	+UsingTheAnnotation():void
	}

+annotation MyAnnotation{
	+{abstract}value():String
	+{abstract}priority():int
	+{abstract}tags():String[]
	}

UsingTheAnnotation..>MyAnnotation : << uses >>
@enduml