@startuml
+class LinterMain{
	+LinterMain():void
	+{static}main(args:String[]):void
	-{static}parseDirectory(stream:Path):List<String>
	-{static}lint(lintType:Set<LintType>, fileOutput:Set<LintType>, stringBuilder:Map<LintType, String>, checks:String, transformations:List<String>, diagrams:Path):List<Message>
	-{static}writeDiagramFiles(fileOutput:String, lintType:LintType, stringBuilder:StringBuilder):void
	-{static}promptUserForDirectory():Path
	-{static}isValidPath(path:String):boolean
	-{static}promptUserForOutputFileName(destinationMessage:String):String
	-{static}promptUserForChecks():Set<LintType>
	-{static}promptUserForPrinciples():Set<LintType>
	-{static}promptUserForPatterns():Set<LintType>
	-{static}promptUserForStyle():Set<LintType>
	-{static}promptUserForTransformations():Set<LintType>
	-{static}promptUserForDiagrams():Map<LintType, String>
	-{static}promptUser(prompt:String):String
	-{static}prettyPrint(message:List<Message>):void
	-{static}saveToFile(message:List<Message>, messages:String):void
	}

@enduml