@startuml
package .. {
	+class CollectionFieldsConverter{
	+ stringList: List<String>
	+ doubleSet: Set<Double>
	- map: Map<String,Integer>
	+ charQueue: Queue<Character>
	+ booleanStack: Stack<Boolean>
	+ advancedMap: Map<List<Set<String>>,List<String>>
	+CollectionFieldsConverter():void
	}

}
@enduml