@startuml
package .. {
	+class ParameterTypeVariety{
	+ParameterTypeVariety():void
	+singlePrimitive(a:int):void
	+multiplePrimitives(a:int, b:double, c:char):void
	+singleObject(s:String):void
	+multipleObjects(s:String, num:Integer, d:Double):void
	+mixPrimitiveAndObject(a:int, b:String, c:double):void
	-withCollections(list:List<String>, set:Set<Character>, map:Map<String,Double>):void
	#withArrayAndList(nums:int[], doubles:List<Double>):void
	~complexParameters(a:int, b:String, nums:List<List<Integer>>, arr:double[], map:Map<String,Set<Character>>):void
	}

}
@enduml