@startuml
package .. {
	+class DependsOnRelations{
	+DependsOnRelations():void
	+hasParams(r:RelationsManager):void
	+hasParams2(r:ImplementingClass):void
	+hasParams3(r:ParameterTypeVariety):void
	+returnsParams():ReturnTypeVariety
	+returnsParams2():ArrayFieldsConverter
	+returnsParams3():AccessModifierVariety
	+testDontAdd(s:String, d:double):String
	}

}
DependsOnRelations..>AccessModifierVariety
DependsOnRelations..>ParameterTypeVariety
DependsOnRelations..>ReturnTypeVariety
DependsOnRelations..>ArrayFieldsConverter
DependsOnRelations..>RelationsManager
DependsOnRelations..>ImplementingClass
@enduml