@startuml
package .. {
	+class HasATest{
	- a: AccessModifierVariety
	- b: ArrayFieldsConverter
	- b2: ArrayFieldsConverter
	- b3: ArrayFieldsConverter
	- c: CollectionFieldsConverter[]
	- d: List<List<ImplementingClass>>
	- e: Set<MockAbstract>
	- f: HashMap<MockEnum,MockInterface>
	- g: ArrayList<AccessModifierVariety>
	- h: Map<HashMap<MockEnum,MockAbstract>,MockInterface>
	- i: Set<HashSet<ObjectFieldsConverter>>
	+HasATest():void
	}

}
HasATest-->AccessModifierVariety
HasATest-->"3"ArrayFieldsConverter
HasATest-->"*"CollectionFieldsConverter
@enduml