package domain;

public enum CheckType {

    ADAPTER_PATTERN,
    FINAL_LOCAL_VARIABLES,
    PLK,
    HIDDEN_FIELDS,
    INTERFACE_OVER_IMPLEMENTATION,
    TEMPLATE_METHOD_PATTERN,
    STRATEGY_PATTERN,
    NAMING_CONVENTION,
    COMPOSITION_OVER_INHERITANCE

}