package domain;

public enum LintType {
    HIDDEN_FIELDS,
    NAMING_CONVENTION,
    FINAL_LOCAL_VARIABLES,
    UNUSED_FIELD,
    INTERFACE_OVER_IMPLEMENTATION,
    COMPOSITION_OVER_INHERITANCE,
    PLK,
    TEMPLATE_METHOD_PATTERN,
    STRATEGY_PATTERN,
    ADAPTER_PATTERN,
    UML_CONVERTER
}
