package domain;

public enum LintType {

    ADAPTER_PATTERN,
    FINAL_LOCAL_VARIABLES,
    PLK,
    HIDDEN_FIELDS,
    INTERFACE_OVER_IMPLEMENTATION,
    TEMPLATE_METHOD_PATTERN,
    STRATEGY_PATTERN,
    NAMING_CONVENTION,
    UNUSED_FIELD, 
    COMPOSITION_OVER_INHERITANCE
}
